version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-magasin-client
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app/src
    environment:
      DATABASE_URL: postgresql://user:password@10.194.32.219:5432/store_db
      POOL_SIZE: 5
      MAX_OVERFLOW: 10